id: AC4CCEA5F
title: Toh_1-1-The_Chapter_on_Going_Forth-v1
type: translation
pechas:
- IA4497016
- IF45DA5BF
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: Text
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-11-02T16:08:06.335Z'
  eft-text-id: UT22084-001-001
  eft-text-version: 1.34.6 2020
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_1-1-The_Chapter_on_Going_Forth-v1
alignment_to_base:
  IA4497016/560B: 172A
  IF45DA5BF/87DF: 172A
